import "../styles/templatemo-video-catalog.css";
import Head from "next/head";
import axios from "axios";
import marked from "marked";

const Home = ({ posts, error }) => {
  let data = null;
  if (error) {
    data = <div>An error occured: {error.message}</div>;
  } else {
    console.log(posts);
    data = (
      <section>
        {posts.map(post => (
          <article key={post.id}>
            <h1>{post.title}</h1>
            <h2>By: {post.author.username}</h2>
            <h3>
              Categories: &nbsp;
              {post.categories.map((category, i) => {
                return <span key={i}>{category.name}</span>;
              })}
            </h3>

            <div dangerouslySetInnerHTML={{ __html: marked(post.content) }}></div>
            {console.log(post.content)}
          </article>
        ))}
      </section>
    );
  }

  return (
    <div>
      <Head>
        <title>Basic Strapi App with Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"></link>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>
      </Head>

      <main>{data}</main>

      <footer></footer>
    </div>
  );
};

export const getServerSideProps = async ctx => {
  try {
    const res = await axios.get("http://localhost:1337/posts");
    const posts = res.data;
    return { props: { posts } };
  } catch (error) {
    return { props: { error } };
  }
};

export default Home;
